### ISSUE TITLE
Switch to overlay folder for packages

### ISSUE THREAD

**Issue by paynejacob** [rancherlabs/corral#43]
The scripts folder should be deprecated in favor of an overlay folder.

The overlay folder will behave like the scripts folder but files will be copied to root instead of `/opt/corral`.   The manifest will also allow for overlay paths to be optionally filtered by prefix and node group. By default all files are copied to all nodes.

```yaml
overlay_filter:
	  -  prefix: /opt
	      node_groups:
	 		- linux
	  - prefix: C:\
	  	 node_groups:
			- wins
```
